Modifications to intel compiler flags when compiling on Windows with Intel compiler
Goddard-Fortran-Ecosystem/gFTL pull request #140
Opened 2021-07-13 17:22 UTC by mbraakhekke

The flags -g, -save-temps, -diag-disable 5462, and -cpp are different for the Windows version of the Intel Fortran compiler.

2021-07-19 12:03 UTC, tclune requested changes
(1) Can you add a small line in the ChangeLog.md  file?   I suppose under the "Fixed" section.
(2) Have you filled out a contributor license agreement?  I unfortunately am required to have one approved by org lawyers before I can accept external contributions.  (See CONTRIBUTING.md in the main directory.)

2021-07-19 20:23 UTC, tclune requested changes
Apologies.  There is a signed CLA.  I had not updated by lists appropriately.

2021-08-04 08:33 UTC, mbraakhekke reviewed
Added a line to ChangeLog.md

2021-08-30 12:57 UTC, tclune approved these changes

2021-08-30 17:21 UTC, merged